'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/app/components/sidebar/Sidebar";
import {UseSidebar} from "@/app/components/sidebar/useSidebar";
import { getPlaylists } from "@/app/lib/api/playlists";
import {EventEmitterProvider, useEventEmitter} from "@/app/contexts/EventEmitterContext";
import Player from "@/app/components/player/Player";
import EventEmitter from "eventemitter3";
import MusicLibrary from "@/app/music-library/MusicLibrary";
import {StoreProvider} from "@/app/StoreProvider";
import {Counter} from "@/app/components/counter/Counter";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    const playlists = await getPlaylists();
    const viewModel = new UseSidebar(playlists);

    return (
        <StoreProvider>
        <html lang="en">
            <body className={inter.className}>
                <Sidebar viewModel={viewModel}/>
                <EventEmitterProvider>
                    {children}
                    <Player />
                </EventEmitterProvider>
            </body>
        </html>
        </StoreProvider>
    );
}
