'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/app/components/sidebar/Sidebar";
import {EventEmitterProvider} from "@/app/contexts/EventEmitterContext";
import Player from "@/app/components/player/Player";
import {StoreProvider} from "@/app/StoreProvider";
import {useAppSelector} from "@/app/lib/hooks";
import {selectPlaylists} from "@/app/lib/features/playlists/playlistsSlice";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    const fetchPlaylists = () => useAppSelector(selectPlaylists);

    return (
        <StoreProvider>
        <html lang="en">
            <body className={inter.className}>
                <Sidebar fetchPlaylists={fetchPlaylists} />
                <EventEmitterProvider>
                    {children}
                    <Player />
                </EventEmitterProvider>
            </body>
        </html>
        </StoreProvider>
    );
}
